### ISSUE TITLE
权重文件精度问题

### ISSUE THREAD

**Issue by snow-seamless** [bollossom/GAC#1]
用百度网盘里面给的权重跑test.py精度只有1%

**Comment by bollossom** [comment]
感谢您关注我们的工作，我这边重新测试了一下权重文件，没有问题，
github上开源的、CODE/CIFAR/models/MS_ResNet.py和权重有的地方有出入，我重新上传了新的网络文件可以重新测试一下

**Comment by bollossom** [comment]
![image](https://github.com/bollossom/GAC/assets/87843847/638bde73-a327-4d57-a639-1db5b8153967)
