### ISSUE TITLE
预训练权重

### ISSUE THREAD

**Issue by liuxida** [bollossom/GAC#11]
作者可以提供一下预训练权重嘛

**Comment by bollossom** [comment]
The weights of CIFAR100 are now open source, see the homepage for details

**Comment by liuxida** [comment]
Yes, I have seen the weight of cifar100, but I need the weight of ImageNet, could you please share it?
Thank  you so much!


---- 回复的原邮件 ----
| 发件人 | Xuerui ***@***.***> |
| 日期 | 2024年10月01日 09:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [bollossom/GAC] 预训练权重 (Issue #11) |

The weights of CIFAR100 are now open source, see the homepage for details
