### ISSUE TITLE
The GAU code connection method is inconsistent with the paper

### ISSUE THREAD

**Issue by sertreet** [bollossom/GAC#12]
Hello author, your work is excellent, but I have a question. In the paper, it is described that spiking occurs after conv+bn, and the GAU is in parallel with this c-b-s (conv-bn-spiking) module. However, the actual code is as follows when self.GAC==True:
x = self.conv1_s(x)
img = x
x = self.spike(x)
x = self.encoding(img, x)
Evidently, the input has been processed through a convolution and then saved as a floating-point image. Afterwards, the spiking signal (x) is generated, and finally, both the spikes and the floating-point image are fed into the GAU, which is inconsistent with the description in the paper.

**Comment by bollossom** [comment]
I apologize for some unclearness in the paper and code. Although the convolution operation is not explicitly used in the GAU code, it can be viewed as a structure that shares parameters with the `conv-bn` part in the mainline code.
