### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'T'

### ISSUE THREAD

**Issue by OuYangLiang0509** [bollossom/GAC#3]
Hello author, very interested in your work, but I am tuning the code is the following error occurs, looking forward to your reply.
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "main.py", line 151, in <module>
    parallel_model =  msresnet18(num_classes=100,T=6)
  File "/home/GAC-main/CODE/CIFAR/models/MS_ResNet.py", line 167, in msresnet18
    return _resnet('resnet18', BasicBlock_MS, [3, 3, 2],
  File "/home/GAC-main/CODE/CIFAR/models/MS_ResNet.py", line 164, in _resnet
    model = ResNet(block, layers, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'T'

**Comment by bollossom** [comment]
Thank you for paying attention to our work. 
I re-tested the training file and modified the code of main.py. 
You can try to re-test it.
