### ISSUE TITLE
TypeError: TET_loss() missing 5 required positional arguments: 'outputs', 'labels', 'criterion', 'means', and 'lamb'     criterion = TET_loss().cuda()

### ISSUE THREAD

**Issue by OuYangLiang0509** [bollossom/GAC#4]
Hello author, very interested in your work, but I am tuning the imagenet code is the following error occurs, looking forward to your reply.
Traceback (most recent call last):
  File "train_amp.py", line 212, in <module>
Traceback (most recent call last):
  File "train_amp.py", line 212, in <module>
    criterion = TET_loss().cuda()
TypeError: TET_loss() missing 5 required positional arguments: 'outputs', 'labels', 'criterion', 'means', and 'lamb'
    criterion = TET_loss().cuda()
TypeError: TET_loss() missing 5 required positional arguments: 'outputs', 'labels', 'criterion', 'means', and 'lamb'

**Comment by bollossom** [comment]
Thank you for paying attention to our work.
I re-tested the training file and modified the code of main.py.
You can try to re-test it.
