### ISSUE TITLE
How do you count the number of spikes and neurons?

### ISSUE THREAD

**Issue by OuYangLiang0509** [bollossom/GAC#6]
Hello author, thank you for your work. How do you count the number of spikes and neurons? Can you provide relevant code?

**Comment by bollossom** [comment]
Thank you for paying attention to our work. This is simple to implement.  Here's a step-by-step refinement:
1. "The output of a spiking neuron is binary: it's either 0 or 1."
2. "Compute the average of the feature maps after each spiking neuron. for example using x.mean()"
3. "Next, sum up these averages to calculate the total firing rate. "
