### ISSUE TITLE
如何计算能量？

### ISSUE THREAD

**Issue by jiaduob** [bollossom/GAC#7]
作者你好，我想询问一下，论文中的能量相关的数据是如何计算的？或者说用什么工具或者包进行统一标准的计算？感谢您的回复

**Comment by bollossom** [comment]
感谢您关注我们的工作。这很容易实现。以下是逐步细化：

脉冲神经元的输出是二进制的：它要么是 0，要么是 1。
计算每个脉冲神经元之后的特征图的平均值。例如使用 x.mean()。
接下来，将这些平均值相加以计算SNN中每一层的发放率。
计算得到发放率之后根据文章中的公式11来计算功耗。

**Comment by jiaduob** [comment]
感谢您的回复

**Comment by jiaduob** [comment]
谢谢您的回复
